import 'package:hive/hive.dart';

// Import generated models (simulated structure)
// In a real project, these would be in the generated folder

/// Simulated Customer model from generator
@HiveType(typeId: 1)
class Customer extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String name;

  @HiveField(2)
  final String email;

  @HiveField(3)
  final DateTime created_at;

  Customer({
    required this.id,
    required this.name,
    required this.email,
    required this.created_at,
  });

  @override
  String toString() =>
      'Customer(id: $id, name: $name, email: $email, created_at: $created_at)';
}

/// Simulated Order model from generator
@HiveType(typeId: 2)
class Order extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final int customer_id;

  @HiveField(2)
  final double price;

  @HiveField(3)
  final DateTime created_at;

  Order({
    required this.id,
    required this.customer_id,
    required this.price,
    required this.created_at,
  });

  @override
  String toString() =>
      'Order(id: $id, customer_id: $customer_id, price: $price, created_at: $created_at)';
}

/// Manual integration test demonstrating Hive usage
Future<void> main() async {
  print('🧪 Starting Hive Integration Test...\n');

  try {
    // Initialize Hive (in real app, use Hive.initFlutter() for Flutter)
    Hive.init('hive_test_data');

    print('✓ Hive initialized\n');

    // Register adapters (manually done since we're not using build_runner output)
    // In a real project with build_runner, the adapters would be auto-generated
    Hive.registerAdapter(CustomerAdapter());
    Hive.registerAdapter(OrderAdapter());
    print('✓ Adapters registered\n');

    // Open boxes
    final customerBox = await Hive.openBox<Customer>('customers');
    final orderBox = await Hive.openBox<Order>('orders');
    print('✓ Boxes opened\n');

    // Test Customer model
    print('--- Testing Customer Model ---\n');
    final customer = Customer(
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
      created_at: DateTime(2024, 3, 6),
    );

    print('Creating customer: $customer');
    await customerBox.put('customer_1', customer);
    print('✓ Customer saved successfully\n');

    final retrievedCustomer = customerBox.get('customer_1');
    print('Retrieved customer: $retrievedCustomer');
    print('✓ Customer retrieved successfully\n');

    // Test Order model
    print('--- Testing Order Model ---\n');
    final order = Order(
      id: 1001,
      customer_id: 1,
      price: 299.99,
      created_at: DateTime(2024, 3, 6),
    );

    print('Creating order: $order');
    await orderBox.put('order_1001', order);
    print('✓ Order saved successfully\n');

    final retrievedOrder = orderBox.get('order_1001');
    print('Retrieved order: $retrievedOrder');
    print('✓ Order retrieved successfully\n');

    // Close boxes
    await customerBox.close();
    await orderBox.close();
    print('--- Integration Complete ---\n');

    print('✅ All integration tests passed!\n');
  } catch (e) {
    print('❌ Error during integration test: $e');
    rethrow;
  }
}

/// Simulated CustomerAdapter (would be auto-generated by hive_generator)
class CustomerAdapter extends TypeAdapter<Customer> {
  @override
  final int typeId = 1;

  @override
  Customer read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Customer(
      id: fields[0] as int,
      name: fields[1] as String,
      email: fields[2] as String,
      created_at: fields[3] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, Customer obj) {
    writer
      ..writeByte(4)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.email)
      ..writeByte(3)
      ..write(obj.created_at);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomerAdapter && runtimeType == other.runtimeType && typeId == other.typeId;
}

/// Simulated OrderAdapter (would be auto-generated by hive_generator)
class OrderAdapter extends TypeAdapter<Order> {
  @override
  final int typeId = 2;

  @override
  Order read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Order(
      id: fields[0] as int,
      customer_id: fields[1] as int,
      price: fields[2] as double,
      created_at: fields[3] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, Order obj) {
    writer
      ..writeByte(4)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.customer_id)
      ..writeByte(2)
      ..write(obj.price)
      ..writeByte(3)
      ..write(obj.created_at);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderAdapter && runtimeType == other.runtimeType && typeId == other.typeId;
}
